mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
]

polls/urls.py
from django.conf.urls import url

from . import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
]

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

polls/models.py
from django.db import models
from tinymce.models import HTMLField

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = HTMLField(blank=False)

tinymce/models.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.db import models
from django.contrib.admin import widgets as admin_widgets
from tinymce import widgets as tinymce_widgets
try:
    from south.modelsinspector import add_introspection_rules
    add_introspection_rules([], ['^tinymce\.models\.HTMLField'])
except ImportError:
    pass


class HTMLField(models.TextField):
    """
    A large string field for HTML content. It uses the TinyMCE widget in
    forms.
    """
    def formfield(self, **kwargs):
        defaults = {'widget': tinymce_widgets.TinyMCE}
        defaults.update(kwargs)

        # As an ugly hack, we override the admin widget
        if defaults['widget'] == admin_widgets.AdminTextareaWidget:
            defaults['widget'] = tinymce_widgets.AdminTinyMCE

        return super(HTMLField, self).formfield(**defaults)

polls/views.py
from .models import Question
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger,InvalidPage
from django.shortcuts import render_to_response


def index(request):
    latest_question_list = Question.objects.all()
    paginator = Paginator(latest_question_list,4)
    try:
        page = int(request.GET.get("page", '1'))
    except ValueError:
        page = 1

    try:
        latest_question_list = paginator.page(page)
    except (InvalidPage, EmptyPage):
        latest_question_list = paginator.page(paginator.num_pages)
    return render_to_response("polls/index.html", dict(latest_question_list=latest_question_list, user=request.user))



def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

tinymce/views.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

import json
import logging

from django.core import urlresolvers
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.encoding import force_text
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_exempt

from tinymce.compressor import gzip_compressor

try:
    import enchant
except ImportError:
    enchant = None


@csrf_exempt
def spell_check(request):
    """
    Returns a HttpResponse that implements the TinyMCE spellchecker protocol.
    """
    try:
        if not enchant:
            raise RuntimeError("install pyenchant for spellchecker functionality")

        raw = force_text(request.body)
        input = json.loads(raw)
        id = input['id']
        method = input['method']
        params = input['params']
        lang = params[0]
        arg = params[1]

        if not enchant.dict_exists(str(lang)):
            raise RuntimeError("dictionary not found for language {!r}".format(lang))

        checker = enchant.Dict(str(lang))

        if method == 'checkWords':
            result = [word for word in arg if word and not checker.check(word)]
        elif method == 'getSuggestions':
            result = checker.suggest(arg)
        else:
            raise RuntimeError("Unknown spellcheck method: {!r}".format(method))
        output = {
            'id': id,
            'result': result,
            'error': None,
        }
    except Exception:
        logging.exception("Error running spellchecker")
        return HttpResponse(_("Error running spellchecker"))
    return HttpResponse(json.dumps(output),
                        content_type='application/json')


def flatpages_link_list(request):
    """
    Returns a HttpResponse whose content is a Javascript file representing a
    list of links to flatpages.
    """
    from django.contrib.flatpages.models import FlatPage
    link_list = [(page.title, page.url) for page in FlatPage.objects.all()]
    return render_to_link_list(link_list)


def compressor(request):
    """
    Returns a GZip-compressed response.
    """
    return gzip_compressor(request)


def render_to_link_list(link_list):
    """
    Returns a HttpResponse whose content is a Javascript file representing a
    list of links suitable for use wit the TinyMCE external_link_list_url
    configuration option. The link_list parameter must be a list of 2-tuples.
    """
    return render_to_js_vardef('tinyMCELinkList', link_list)


def render_to_image_list(image_list):
    """
    Returns a HttpResponse whose content is a Javascript file representing a
    list of images suitable for use wit the TinyMCE external_image_list_url
    configuration option. The image_list parameter must be a list of 2-tuples.
    """
    return render_to_js_vardef('tinyMCEImageList', image_list)


def render_to_js_vardef(var_name, var_value):
    output = "var {!s} = {!s};".format(var_name, json.dumps(var_value))
    return HttpResponse(output, content_type='application/x-javascript')


def filebrowser(request):
    try:
        fb_url = request.build_absolute_uri(urlresolvers.reverse('fb_browse'))
    except:
        fb_url = request.build_absolute_uri(urlresolvers.reverse('filebrowser:fb_browse'))

    return render(
        request,
        'tinymce/filebrowser.js',
        {'fb_url': fb_url},
        content_type='application/javascript'
    )

polls/templates/base.html
{% load staticfiles %}
<html>
<head>

    <title> {% block title %} MY Base Template{% endblock  %}</title>
      <link rel="stylesheet" type="text/css" href="{% static "css/default.css" %}" />

</head>


<body>


<div class="head" >
  <p>This is a paragraph.</p>
</div>

<div id="page">
    <div id="sidebar">
{% block sidebar %}
    <ul>
    <li><a href="{% url 'polls:index' %}">Article</a></li>

    <li><a href="/admin/"> admin</a></li>
    </ul>
        {% endblock %}

        </div>

    </div>

<div id="content">
    {% block content %}{% endblock %}


    </div>
<div>
    <footer>Copyright © W3Schools.com</footer>
    </div>


</body>
</html>

polls/templates/polls/detail.html
{% extends "base.html" %}
{% block content %}
    <div class="content1" >
<h1>{{ question.question_text }}</h1>

     <p>{{ question.body }}</p>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% block content %}
{% if latest_question_list %}


    {% for question in latest_question_list %}
 <div class="content1" >
       <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

        <p>{{ question.body|lower|truncatewords:"20" }}</p>
        <a href="{% url 'polls:detail' question.id %}">Read More </a>
        </div>
    {% endfor %}

{% else %}
    <p>No polls are available.</p>

{% endif %}


  <div class="pagination" >
            <span class="step-links">
                {% if latest_question_list.has_previous %}



                     <li style="display:inline;"><a href= "?page={{ latest_question_list.previous_page_number }}" >prev </a></li>

                {% endif %}
                {%for pg in latest_question_list.paginator.page_range%}
                {%if latest_question_list.number == pg %}

                <li style="display:inline;" class="current"><a href="?page={{pg}}">{{pg}}</a></li>
                {%else%}
                 <li style="display:inline;" class="current"><a href="?page={{pg}}">{{pg}}</a></li>
                {%endif%}
                {%endfor%}

                </span>

                {% if latest_question_list.has_next %}

                     <li style="display:inline;"><a href="?page={{ latest_question_list.next_page_number }}" >Next </a></li>

                {% endif %}
            </span>
        </div>
{% endblock %}

templates/polls/base.html
<html>
<head>
    <title> {% block title %} MY Base Template{% endblock  %}</title>
    <style type="text/css">
        body{ text-align: center}
        #page{
            width: 960px;
            text-align: left;
            margin: 10px auto 20px auto;
            background-color: #0c0c0c;

        }
        #sidebar{
            float: left;
            width: 200px;
            border: 1px solid #000;


        }
        #content{
            float: left;
            width: 600px;
            border: 1px solid #f00;
            padding: 10px;

        }

        </style>
</head>


<body>

<div id="page">
    <div id="sidebar">
{% block sidebar %}
    <ul>
    <li><a href=""></a></li>

    <li><a href=""></a></li>
    </ul>
        {% endblock %}

        </div>

    </div>

<div id="content">
    {% block content %}{% endblock %}

    </div>

</body>
</html>

tinymce/templates/tinymce/preview_javascript.html
<script language="javascript" src="{{ base_url }}/tiny_mce_popup.js"></script>
<script type="text/javascript"
src="{{ base_url }}/plugins/preview/jscripts/embed.js"></script>
<script type="text/javascript">
    tinyMCEPopup.onInit.add(function(ed) {
        var dom = tinyMCEPopup.dom;

        dom.setHTML('{{ element_id }}', ed.getContent());
    });

    document.write('<base href="' + tinyMCEPopup.getWindowArg("base") + '">');
</script>